### ISSUE TITLE
Project initializer for Teal

### ISSUE THREAD

**Issue by mikatuo** [mikatuo/vscode-defold-buddy#8]
With added [Teal annotations](https://github.com/mikatuo/defold-lua-annotations/pull/5) they can be used to automate Defold project setup with Teal, similar to Lua annotations.

## TODO
- [x] when running "Initialize" command ask user to select if they want to add annotations for Lua or Teal
- [x] if user chooses Teal then download `defold-teal-{version}.zip`
- [x] extract the `defold.d.tl` file and copy it into the Defold project `types` folder
- [x] update tlconfig.lua to include global_env_def = "defold":
  ```lua
  return {
      gen_target = "5.1",
      gen_compat = "off",
      include_dir = {
          ".defold/api/"
      },
      include = {"**/*.tl"},
      global_env_def = "defold",
  }
  ```
- [x] add `defold.d.tl` into `.gitignore`
- [x] show Teal readme
- [x] add `extension-teal` into `game.project`

**Comment by mikatuo** [comment]
https://github.com/mikatuo/vscode-defold-buddy/blob/main/src/utils/config-initializer.ts and https://github.com/mikatuo/vscode-defold-buddy/blob/main/src/commands/initialize-command.ts would be good starting points to get familiar with setup for Lua.

**Comment by mikatuo** [comment]
Added Teal project initializer https://github.com/mikatuo/vscode-defold-buddy/commit/a7a1e89c85e1e27ddebe13889c171606c497d7fc
